from bridgeconst.consts import Chain, Asset

SUPPORTING_MAIN_CHAINS = [Chain.BFC_MAIN, Chain.ETH_MAIN, Chain.BNB_MAIN, Chain.MATIC_MAIN]


ASSET_ON_BFC_MAIN = [
    # BFC
    Asset.BFC_ON_BFC_MAIN,  # coin
    Asset.BRIDGED_ETH_MAIN_BFC_ON_BFC_MAIN,
    Asset.UNIFIED_BFC_ON_BFC_MAIN,  # wbfc

    # BIFI
    Asset.BRIDGED_ETH_MAIN_BIFI_ON_BFC_MAIN,
    Asset.UNIFIED_BIFI_ON_BFC_MAIN,

    # ETH
    Asset.BRIDGED_ETH_MAIN_ETH_ON_BFC_MAIN,
    Asset.UNIFIED_ETH_ON_BFC_MAIN,

    # BNB
    Asset.BRIDGED_BNB_MAIN_BNB_ON_BFC_MAIN,
    Asset.UNIFIED_BNB_ON_BFC_MAIN,

    # MATIC
    Asset.BRIDGED_MATIC_MAIN_MATIC_ON_BFC_MAIN,
    Asset.UNIFIED_MATIC_ON_BFC_MAIN,

    # USDC
    Asset.BRIDGED_BNB_MAIN_USDC_ON_BFC_MAIN,
    Asset.BRIDGED_ETH_MAIN_USDC_ON_BFC_MAIN,
    Asset.UNIFIED_USDC_ON_BFC_MAIN,

    # USDC
    Asset.BRIDGED_ETH_MAIN_SAT_ON_BFC_MAIN,
    Asset.UNIFIED_SAT_ON_BFC_MAIN
]

ASSET_ON_ETH_MAIN = [
    Asset.BFC_ON_ETH_MAIN,
    Asset.BIFI_ON_ETH_MAIN,
    Asset.ETH_ON_ETH_MAIN,
    Asset.USDC_ON_ETH_MAIN,
    Asset.SAT_ON_ETH_MAIN
]

ASSET_ON_BNB_MAIN = [
    Asset.BNB_ON_BNB_MAIN,
    Asset.USDC_ON_BNB_MAIN
]

ASSET_ON_MATIC_MAIN = [
    Asset.MATIC_ON_MATIC_MAIN
]

SUPPORTING_ASSETS = ASSET_ON_BFC_MAIN + ASSET_ON_ETH_MAIN + ASSET_ON_BNB_MAIN + ASSET_ON_MATIC_MAIN
